package estructuradatosavanzada;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.xml.bind.JAXB;

/**
 * @author Quiroz Vargas
 * 
 * En esta clase se incluyen: un objeto tipo Arbol(), y el numero de hojas que 
 * se desea tener el arbol = 2^K.     
 */
public class GUISMC extends javax.swing.JDialog {

    private Arbol smc;
    private final int cantHojas = 8;
    /** Creates new form GuiSMC */
    public GUISMC(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        smc = new Arbol(cantHojas);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sumaMC = new javax.swing.JButton();
        entero1 = new javax.swing.JTextField();
        entero2 = new javax.swing.JTextField();
        entero3 = new javax.swing.JTextField();
        entero4 = new javax.swing.JTextField();
        generarNumeros = new javax.swing.JButton();
        outSMC = new javax.swing.JTextField();
        entero6 = new javax.swing.JTextField();
        entero7 = new javax.swing.JTextField();
        entero8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        entero5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        sumaMC.setText("SMC");
        sumaMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaMCActionPerformed(evt);
            }
        });

        entero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entero4ActionPerformed(evt);
            }
        });

        generarNumeros.setText("Generar Numeros");
        generarNumeros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generarNumerosMouseClicked(evt);
            }
        });

        outSMC.setEditable(false);

        entero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entero6ActionPerformed(evt);
            }
        });

        entero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entero7ActionPerformed(evt);
            }
        });

        entero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entero8ActionPerformed(evt);
            }
        });

        jLabel1.setText("Suma Maxima Consecutiva");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(outSMC, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(entero1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(entero2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(entero3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(entero4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(entero5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(generarNumeros)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(entero6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sumaMC))
                        .addGap(14, 14, 14)
                        .addComponent(entero7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(entero8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entero4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entero8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entero5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entero7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entero6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generarNumeros)
                    .addComponent(sumaMC))
                .addGap(35, 35, 35)
                .addComponent(outSMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getEntero5() {
        return entero5;
    }

    public void setEntero5(JTextField entero5) {
        this.entero5 = entero5;
    }

    public JTextField getEntero6() {
        return entero6;
    }

    public void setEntero6(JTextField entero6) {
        this.entero6 = entero6;
    }

    public JTextField getEntero7() {
        return entero7;
    }

    public void setEntero7(JTextField entero7) {
        this.entero7 = entero7;
    }

    public JTextField getEntero8() {
        return entero8;
    }

    public void setEntero8(JTextField entero8) {
        this.entero8 = entero8;
    }

    private void entero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entero4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entero4ActionPerformed

    /**
     * Metodo que se ejecuta al hacer click en el boton SMC, y que muestra la 
     * solucion del SMC. 
     */
    private void sumaMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaMCActionPerformed
        try {
            if (getEntero1().getText().equals("")) {
                throw new Exception("Debes Generar Valores !");
            }

            getSmc().crearArbol(getSmc().getRaiz());
            getSmc().llenarValores(getSmc().getRaiz(), getSmc().getHojas());
            pintarPivotes(getSmc().getRaiz().getIntervaloM().getComienzo(),getSmc().getRaiz().getIntervaloM().getFin());
            getOutSMC().setText("El Peso Maximo: " + getSmc().getRaiz().getIntervaloM().getPeso() + ", Comienza en: " + getSmc().getRaiz().getIntervaloM().getComienzo() + " Hasta: " + getSmc().getRaiz().getIntervaloM().getFin());
            
        } catch (Exception e) {
            //Logger.getLogger(GUISMC.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, e.getMessage());
        } finally {
            getSmc().setPosi(0);
        }
    }//GEN-LAST:event_sumaMCActionPerformed
    
    /**
     * Metodo encargado de setear en los atributos entero1,entero2,entero3,
     * entero4,entero5,entero6,entero7,entero8; los numeros generados aleatoriamente
     * por el Arbol SMC
     */
    private void generarNumerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generarNumerosMouseClicked
        getOutSMC().setText("");
        getSmc().generaNumerosAleatorios();
        int arre[] = getSmc().getHojas();
        
        try {
            getEntero1().setText("" + arre[0]);
            getEntero2().setText("" + arre[1]);
            getEntero3().setText("" + arre[2]);
            getEntero4().setText("" + arre[3]);
            getEntero5().setText("" + arre[4]);
            getEntero6().setText("" + arre[5]);
            getEntero7().setText("" + arre[6]);
            getEntero8().setText("" + arre[7]);


        } catch (Exception e) {
            //System.out.println("Intervalo con excepcion");
        } finally{
            descolorear();
        }
    }//GEN-LAST:event_generarNumerosMouseClicked
    
    /**
     * Metodo que colorea de verde a los atributos(jTexfield)
     * entero1,entero2,entero3,entero4,entero5,entero6,entero7,entero8
     * que estan dentro de la solucion SMC.      
     */
    private void pintarPivotes(int desde, int hasta){

        switch(desde){
            case 0:getEntero1().setBackground(Color.green);
            case 1:getEntero2().setBackground(Color.green);
            case 2:getEntero3().setBackground(Color.green);
            case 3:getEntero4().setBackground(Color.green);
            case 4:getEntero5().setBackground(Color.green);
            case 5:getEntero6().setBackground(Color.green);
            case 6:getEntero7().setBackground(Color.green);
            case 7:getEntero8().setBackground(Color.green);
            default:break;

        }

        switch(hasta+1){
            case 0:getEntero1().setBackground(Color.white);
            case 1:getEntero2().setBackground(Color.white);
            case 2:getEntero3().setBackground(Color.white);
            case 3:getEntero4().setBackground(Color.white);
            case 4:getEntero5().setBackground(Color.white);
            case 5:getEntero6().setBackground(Color.white);
            case 6:getEntero7().setBackground(Color.white);
            case 7:getEntero8().setBackground(Color.white);
            default:break;

        }
 
    }
    
    /**
     * Metodo que descolorea o vuelve a pintar de blanco los atributos(jTexfield)
     * entero1,entero2,entero3,entero4,entero5,entero6,entero7,entero8.     
     */
    private void descolorear(){
        getEntero1().setBackground(Color.white);
        getEntero2().setBackground(Color.white);
        getEntero3().setBackground(Color.white);
        getEntero4().setBackground(Color.white);
        getEntero5().setBackground(Color.white);
        getEntero6().setBackground(Color.white);
        getEntero7().setBackground(Color.white);
        getEntero8().setBackground(Color.white);
    }

    private void entero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entero6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entero6ActionPerformed

    private void entero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entero7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entero7ActionPerformed

    private void entero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entero8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entero8ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
               
                GUISMC dialog = new GUISMC(new javax.swing.JFrame(), true);
                dialog.setTitle("Suma Maxima Consecutiva");
                dialog.getSmc().calcularAlturaArbol();
              
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entero1;
    private javax.swing.JTextField entero2;
    private javax.swing.JTextField entero3;
    private javax.swing.JTextField entero4;
    private javax.swing.JTextField entero5;
    private javax.swing.JTextField entero6;
    private javax.swing.JTextField entero7;
    private javax.swing.JTextField entero8;
    private javax.swing.JButton generarNumeros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField outSMC;
    private javax.swing.JButton sumaMC;
    // End of variables declaration//GEN-END:variables

    /**
     * Setter's y Getter's para cada atributo de la clase GUISMC
     */
    public JTextField getEntero1() {
        return entero1;
    }

    public void setEntero1(JTextField entero1) {
        this.entero1 = entero1;
    }

    public JTextField getEntero2() {
        return entero2;
    }

    public void setEntero2(JTextField entero2) {
        this.entero2 = entero2;
    }

    public JTextField getEntero3() {
        return entero3;
    }

    public void setEntero3(JTextField entero3) {
        this.entero3 = entero3;
    }

    public JTextField getEntero4() {
        return entero4;
    }

    public void setEntero4(JTextField entero4) {
        this.entero4 = entero4;
    }

    /**
     * @return the smc
     */
    public Arbol getSmc() {
        return smc;
    }

    /**
     * @param smc the smc to set
     */
    public void setSmc(Arbol smc) {
        this.smc = smc;
    }

    /**
     * @return the outSMC
     */
    public javax.swing.JTextField getOutSMC() {
        return outSMC;
    }

    /**
     * @param outSMC the outSMC to set
     */
    public void setOutSMC(javax.swing.JTextField outSMC) {
        this.outSMC = outSMC;
    }

}
